"""Naming contract between training output filenames and app.py's model
discovery.

app.py locates model files with a glob of the shape
``*.{tpModelName}.*.pos{T|F}.pt`` (see ``_annotate_timepoints``), so the
suffix generated by train.py must keep ``pos{T,F}`` as its final
component and the ``T``/``F`` flag must truthfully reflect
``pos_vec_coeff``. If either side of this contract changes, both must
change together, along with these tests.
"""
import copy
import fnmatch

import pytest

pytest.importorskip('torch')
pytest.importorskip('torchvision')
pytest.importorskip('transformers')

from modeling import gridsearch, train

# mirrors the literal glob in app.py _annotate_timepoints
APP_GLOB = '*.{model}.*.pos{tf}.pt'

GRID_CONFIGS = [copy.deepcopy(c)
                for c in gridsearch.get_classifier_training_grids()]


def suffix_of(config):
    # the normalizer mutates its argument, so hand it a copy
    return train.normalize_config_and_get_train_id_suffix_from_config(
        copy.deepcopy(config))


@pytest.mark.parametrize('config', GRID_CONFIGS)
def test_suffix_ends_with_pos_flag(config):
    expected = 'posF' if config['pos_vec_coeff'] == 0 else 'posT'
    suffix = suffix_of(config)
    assert suffix.split('.')[-1] == expected


@pytest.mark.parametrize('config', GRID_CONFIGS)
def test_suffix_has_no_seed_component(config):
    # the seed is train-time bookkeeping only: it lives in the exported
    # yml and the config hash, never in the suffix, because the app's
    # glob requires filenames to end in .pos{T,F}.pt
    assert 'seed' not in suffix_of(dict(config, seed=4))


@pytest.mark.parametrize('config', GRID_CONFIGS)
def test_filename_matches_app_glob(config):
    suffix = suffix_of(config)
    # train id shape: {prefix}.{config_hash}.{suffix}
    fname = f'20990101-000000.0123abcd4567.{suffix}.pt'
    pattern = APP_GLOB.format(
        model=config['img_enc_name'],
        tf='F' if config['pos_vec_coeff'] == 0 else 'T')
    assert fnmatch.fnmatch(fname, pattern), (fname, pattern)


def test_seed_does_not_change_suffix():
    base = GRID_CONFIGS[0]
    assert (suffix_of(dict(base, seed=1))
            == suffix_of(dict(base, seed=2)))


if __name__ == '__main__':
    pytest.main([__file__])
