model_file: "modeling/models/20231026-164841.kfold_000.pt"
model_config: "modeling/models/20231026-164841.config.yaml"
step_size: 1000
minimum_score: 1.01
safe_frames: False
dribble: False
score_mapping: {0.01: 0, 0.25: 1, 0.50: 2, 0.75: 3, 1.01: 4}