# Default run-time configuration settings
# Some of these can be changed by setting parameters when running SWT as an app

# The model file and its configuration settings
# May want to use 20231026-164841.kfold_results.txt as well
model_file: "modeling/models/20231026-164841.kfold_000.pt"
model_config: "modeling/models/20231026-164841.config.yml"

# Time unit for output timeframe
time_unit: 'milliseconds'

# Milliseconds between sampled frames
sample_rate: 1000

# Minimum score for a frame to be included in a potential timeframe
minimum_frame_score: 0.01

# Minimum score for a timeframe to be selected
minimum_timeframe_score: 0.25

# Minimum number of sampled frames required for a timeframe to be included
minimum_frame_count: 2

# Debugging setting
dribble: False
