model_file: "modeling/models/20231102-165708.kfold_000.pt"
sample_rate: 1000
minimum_score: 1.01
score_mapping: {0.01: 0, 0.25: 1, 0.50: 2, 0.75: 3, 1.01: 4}

img_enc_name: "convnext_lg"
pos_enc_name: "sinusoidal-concat"
pos_enc_dim: 512
max_input_length: 5640000
position_unit: 60000

feature_dim: 2048
num_layers: 2
dropouts: 0.2

prebin: 
  - bars
  - slate
  - chyron
  - text-not-chyron
  - person-not-chyron
  - credits
  - other
labels: [ "slate", "chyron", "credit", "other" ]
postbin:
  0: 3
  1: 0
  2: 1
  3: 3
  4: 3
  5: 2
  6: 3
  
