model_file: "modeling/models/20240409-091401.convnext_lg.pt"
model_config_file: "modeling/models/20240409-091401.convnext_lg.yml"

# Milliseconds between sampled frames
sampleRate: 1000

# Minimum score for a frame to be included in a potential timeframe
minFrameScore: 0.01

# Minimum score for a timeframe to be selected
minTimeframeScore: 0.5

# Minimum number of sampled frames required for a timeframe to be included
minFrameCount: 2

# These are time frames that are typically static (that is, the text does not
# move around or change as with rolling credits). These are frame names after
# the label mapping.
staticFrames: [bars, slate, chyron]

# Set to False to turn off the stitcher
useStitcher: True

# This was the most frequent label mapping the previous configuration file,
# which had default mappings for each model.
labelMap: [
    "B:bars",
    "S:slate", "S-H:slate", "S-C:slate", "S-D:slate", "S-G:slate",
    "W:other_opening", "L:other_opening", "O:other_opening", "M:other_opening",
    "I:chyron", "N:chyron", "Y:chyron",
    "C:credit", "R:credit",
    "E:other_text", "K:other_text", "G:other_text", "T:other_text", "F:other_text" ]
