model_file: "modeling/models/20240126-180026.convnext_lg.kfold_000.pt"
model_config_file: "modeling/models/20240126-180026.convnext_lg.kfold_config.yml"

# Milliseconds between sampled frames
sampleRate: 1000

# Minimum score for a frame to be included in a potential timeframe
minFrameScore: 0.01

# Minimum score for a timeframe to be selected
minTimeframeScore: 0.5

# Minimum number of sampled frames required for a timeframe to be included
minFrameCount: 2

# These are time frames that are typically static (that is, the text does not
# move around or change as with rolling credits)
staticFrames: [bars, slate, chyron]
