model_file: "modeling/models/20240409-091401.convnext_lg.kfold_013.pt"
model_config_file: "modeling/models/20240409-091401.convnext_lg.kfold_config.yml"

# Milliseconds between sampled frames
sampleRate: 1000

# Minimum score for a frame to be included in a potential timeframe
minFrameScore: 0.01

# Minimum score for a timeframe to be selected
minTimeframeScore: 0.5

# Minimum number of sampled frames required for a timeframe to be included
minFrameCount: 2

# These are time frames that are typically static (that is, the text does not
# move around or change as with rolling credits)
staticFrames: [bars, slate, chyron]

# Set to False to turn off the stitcher
useStitcher: True

postbins:
  20240126-180026.convnext_lg.kfold_000:
    bars:
      - B
    slate:
      - S
      - S:H
      - S:C
      - S:D
      - S:G
    chyron:
      - I
      - N
      - Y
    credits:
      - C
  20240212-131937.convnext_tiny.kfold_000: 
    bars:
      - "B"
    slate:
      - "S"
      - "S:H"
      - "S:C"
      - "S:D"
      - "S:G"
    other_opening:
      - "W"
      - "L"
      - "O"
      - "M"
    chyron:
      - "I"
      - "N"
      - "Y"
    credit:
      - "C"
      - "R"
    other_text:
      - "E"
      - "K"
      - "G"
      - 'T'
      - 'F'
  20240212-132306.convnext_lg.kfold_000:
    bars:
      - "B"
    slate:
      - "S"
      - "S:H"
      - "S:C"
      - "S:D"
      - "S:G"
    other_opening:
      - "W"
      - "L"
      - "O"
      - "M"
    chyron:
      - "I"
      - "N"
      - "Y"
    credit:
      - "C"
      - "R"
    other_text:
      - "E"
      - "K"
      - "G"
      - 'T'
      - 'F'
  20240409-091401.convnext_lg.kfold_013:
    bars:
      - "B"
    slate:
      - "S"
      - "S:H"
      - "S:C"
      - "S:D"
      - "S:G"
    other_opening:
      - "W"
      - "L"
      - "O"
      - "M"
    chyron:
      - "I"
      - "N"
      - "Y"
    credit:
      - "C"
      - "R"
    other_text:
      - "E"
      - "K"
      - "G"
      - 'T'
      - 'F'
  20240409-093229.convnext_tiny.kfold_012:
    bars:
      - "B"
    slate:
      - "S"
      - "S:H"
      - "S:C"
      - "S:D"
      - "S:G"
    other_opening:
      - "W"
      - "L"
      - "O"
      - "M"
    chyron:
      - "I"
      - "N"
      - "Y"
    credit:
      - "C"
      - "R"
    other_text:
      - "E"
      - "K"
      - "G"
      - 'T'
      - 'F'
