model_file: "modeling/models/20231214-191952.convnext_tiny.kfold_000.pt"
model_config_file: "modeling/models/20231214-193543.convnext_tiny.kfold_config.yml"

# Milliseconds between sampled frames
sample_rate: 1000

# Minimum score for a frame to be included in a potential timeframe
minimum_frame_score: 0.01

# Minimum score for a timeframe to be selected
minimum_timeframe_score: 0.25

# Minimum number of sampled frames required for a timeframe to be included
minimum_frame_count: 2
