num_epochs: 5
num_splits: 5
backbone_name: "convnext_tiny"
block_guids_train: ["cpb-aacip-254-75r7szdz"]
block_guids_valid: [
    "cpb-aacip-254-75r7szdz",
    "cpb-aacip-259-4j09zf95",
    "cpb-aacip-526-hd7np1xn78",
    "cpb-aacip-75-72b8h82x",
    "cpb-aacip-fe9efa663c6",
    "cpb-aacip-f5847a01db5",
    "cpb-aacip-f2a88c88d9d",
    "cpb-aacip-ec590a6761d",
    "cpb-aacip-c7c64922fcd",
    "cpb-aacip-f3fa7215348",
    "cpb-aacip-f13ae523e20",
    "cpb-aacip-e7a25f07d35",
    "cpb-aacip-ce6d5e4bd7f",
    "cpb-aacip-690722078b2",
    "cpb-aacip-e649135e6ec",
    "cpb-aacip-15-93gxdjk6",
    "cpb-aacip-512-4f1mg7h078",
    "cpb-aacip-512-4m9183583s",
    "cpb-aacip-512-4b2x34nt7g",
    "cpb-aacip-512-3n20c4tr34",
    "cpb-aacip-512-3f4kk9534t",
  ]
num_layers: 3
positional_encoding: "fractional"
unit_multiplier: 60000
embedding_size: 512
dropouts: 0.1
bins:
  pre:
    slate:
      - "S"
    chyron:
      - "I"
      - "N"
      - "Y"
    credit:
      - "C"
