num_epochs: 2
num_splits: 2
backbone_name: "vgg16"
block_guids_train: []
block_guids_valid: []
num_layers: 3
dropouts: 0.2
bins:
  pre:
    slate:
      - "S"
    chyron:
      - "I"
      - "N"
      - "Y"
    credit:
      - "C"